### ISSUE TITLE
Pyload-Ng?

### ISSUE THREAD

**Issue by gerroon** [RemiRigal/Yape#7]
Hi

Is this compatible with Payload-Ng? I cant seem to be able to submit Youtube downloads to it.  

I am using the Pyload-NG from Linuxserver.io

**Comment by RemiRigal** [comment]
Thanks for the issue, it indeed appears that the API of PyLoad-ng is not implemented according to the official docs, I will have to investigate more. I'll keep you updated.

**Comment by gerroon** [comment]
Hi

Do you know if you will be able to support Pyload-Ng? It seems like Linuxserver does not provide old Pyload Dockers anymore.

**Comment by RemiRigal** [comment]
Hi @gerroon ! This issue is actually a bug from PyLoad's end, but it should be fixed in a few days/weeks, see the following issue for more details: https://github.com/pyload/pyload/issues/4095.
I'll let you know when this is fixed.

**Comment by gerroon** [comment]
Thanks for the follow up. That sounds great.

**Comment by milahu** [comment]
still not working with [Yape from crx4chrome](https://www.crx4chrome.com/extensions/lbbofcfllogcmffofacfoiolglncdcgb/)

`chrome-extension://lbbofcfllogcmffofacfoiolglncdcgb/popup.html`

```
popup.js:28 Uncaught TypeError: status.forEach is not a function
    at popup.js:28:16
    at XMLHttpRequest.xhr.onreadystatechange (pyload-api.js:53:27)
(anonymous) @ popup.js:28
xhr.onreadystatechange @ pyload-api.js:53
XMLHttpRequest.send (async)
getStatusDownloads @ pyload-api.js:56
updateStatusDownloads @ popup.js:25
(anonymous) @ popup.js:129
(anonymous) @ storage.js:17
xhr.onreadystatechange @ pyload-api.js:12
XMLHttpRequest.send (async)
getServerStatus @ pyload-api.js:23
isLoggedIn @ storage.js:15
(anonymous) @ popup.js:121
(anonymous) @ storage.js:10

pyload-api.js:84 Uncaught TypeError: JSON.parse(...).toLowerCase is not a function
    at XMLHttpRequest.xhr.onreadystatechange (pyload-api.js:84:61)
xhr.onreadystatechange @ pyload-api.js:84
XMLHttpRequest.send (async)
getLimitSpeedStatus @ pyload-api.js:88
updateLimitSpeedStatus @ popup.js:17
(anonymous) @ popup.js:132
(anonymous) @ storage.js:17
xhr.onreadystatechange @ pyload-api.js:12
XMLHttpRequest.send (async)
getServerStatus @ pyload-api.js:23
isLoggedIn @ storage.js:15
(anonymous) @ popup.js:121
(anonymous) @ storage.js:10

pyload-api.js:67 Uncaught TypeError: queueData.forEach is not a function
    at XMLHttpRequest.xhr.onreadystatechange (pyload-api.js:67:23)
xhr.onreadystatechange @ pyload-api.js:67
XMLHttpRequest.send (async)
getQueueData @ pyload-api.js:75
(anonymous) @ popup.js:144
xhr.onreadystatechange @ pyload-api.js:129
XMLHttpRequest.send (async)
checkURL @ pyload-api.js:132
(anonymous) @ popup.js:139
```
